add: materi class
bellshade/Dart pull request #33
Opened 2021-11-20 12:50 UTC by zalviandyr

## Deskripsi (Description)

- [x] saya menambahkan algoritma terbaru
- [ ] saya memperbaiki algoritma yang sudah ada
- [x] saya memperbaiki dokumentasi
- [x] saya menambah dokumentasi

## Syarat Kontributor (Contributor Requirements)

- [x] saya sudah membaca (i have read) dan sudah menyetujui (agree) semua yang ada di [CONTRIBUTING](https://github.com/bellshade/Dart/blob/main/CONTRIBUTING.md)
- [x] saya telah menambahkan docs yang memberikan penjelasan maksud dari kode yang saya buat
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## Lingkungan (Environment)

saya menggunakan (im used):

- [x] versi Dart terbaru

## Testing

- [ ] analyze lint Dart
- [ ] doctesting Dart

## Maintainer
request maintainer untuk mereiview kode kamu usahakan kamu memilih sesuai apa yang telah kamu ubah

**maintainer dart**
@bellshade/dart-team

**maintainer dokumentasi**
@bellshade/docs-team

> [ID ] Jika ada gagal pada salah satu test kami akan mengeceknya kembali

> [EN] If there is a failure in one of the tests we will check it again

2021-11-22 05:27 UTC, aditjoos requested changes
LGTM!
Terimakasih sudah berkontribusi, om 👍 
Hanya saja ada typo yang harus diubah sedikit 🛠️

2021-11-22 05:27 UTC, aditjoos commented on lanjutan/3_class/Readme.md
> +Akan tetapi kita bisa membuat hal tersebut menjadi lebih sederhana menggunakan **Cascase Operator**.
Typo, harusnya "Cascade"

2021-11-22 05:27 UTC, aditjoos commented on lanjutan/3_class/Readme.md
> +Perlu diperhatikan posisi titik koma berada di akhir pada saat selesai menggunakan **Cascase Operator**.
Typo, harusnya "Cascade"

2021-11-23 03:18 UTC, aditjoos approved these changes
Noice 🚀

2021-11-23 04:12 UTC, nomadkode approved these changes
LGTM 🔥

2021-11-23 04:42 UTC, merged