docs: Update readme
bellshade/Dart pull request #50
Opened 2021-12-27 14:10 UTC by amdev142

## Deskripsi (Description)

- [ ] Saya menambahkan algoritma terbaru
- [ ] Saya memperbaiki algoritma yang sudah ada
- [x] Saya memperbaiki dokumentasi
- [x] Saya menambah dokumentasi

## Syarat Kontributor (Contributor Requirements)

- [x] Saya sudah membaca dan menyetujui semua peraturan yang ada di [CONTRIBUTING.md](https://github.com/bellshade/Dart/blob/main/CONTRIBUTING.md)
- [x] Saya telah menambahkan docs yang memberikan penjelasan maksud dari kode yang Saya buat
- [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang Saya buat

## Lingkungan

Saya menggunakan:

- [ ] versi Dart terbaru

## Testing

- [ ] analyze lint Dart
- [ ] doctesting Dart

## Issue

Issue: 

---
> [ID] Jika ada gagal pada salah satu test kami akan mengeceknya kembali
> [EN] If there is a failure in one of the tests we will check it again

2021-12-28 14:17 UTC, aditjoos requested changes
Haloo om, docs sudah aman mantap 👍 
Tapi apakah bisa ditambahkan juga update untuk file `.dart` sesuai materi yang ditambahkan?

2021-12-28 14:17 UTC, aditjoos commented
@nomadkode docs bisa approve 🚀

2021-12-29 07:23 UTC, amdev142 commented
kemarin mau saya tambahkan om. cuma saya pikir2 lagi and gamau ambil ribet soal testing code jadi saya skip hahaha

2021-12-29 07:25 UTC, amdev142 commented
untuk doc ada yang saya lupa tambahin yaitu: required parameter.. mohon bantuannya bagi helper dart untuk menambahkan nya

2021-12-29 07:27 UTC, amdev142 commented
eh udah ada required parameter ternyata saya kira blm

2021-12-31 03:15 UTC, aditjoos commented
> kemarin mau saya tambahkan om. cuma saya pikir2 lagi and gamau ambil ribet soal testing code jadi saya skip hahaha

kalau codenya simple, engga seperti algoritma, mungkin bisa skip/biarin aja testingnya om hehe 🏃

2021-12-31 22:38 UTC, amdev142 commented
Sudah saya tambahkan ke file dart, dart beberapa koreksi kode di docs sudah saya perbaiki

2021-12-31 22:42 UTC, amdev142 commented
saya commit ulang lupa uncomment pas testing code wkwkw

2022-01-03 02:01 UTC, aditjoos approved these changes
noice, makasih ✨

2022-01-04 04:48 UTC, nomadkode approved these changes

2022-01-06 10:37 UTC, merged